server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: analysis-agent
#  ai:
#    alibaba:
#      toolcalling:
#        aliyunaisearch:
#          api-key: ${ALIYUN_SEARCH_API_KEY}
#          base-url: ${ALIYUN_SEARCH_BASE_URL}
#          enabled: true

    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          #          model: qwen-plus
          model: qwen3-max

  mandatory-file-encoding: UTF-8