server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: analysis-agent
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          #          model: qwen-plus
          model: qwen3-max
    mcp:
      client:
        sse:
          connections:
            server1:
              url: https://dashscope.aliyuncs.com/
              sse-endpoint: /api/v1/mcps/zhipu-websearch/sse
              # 定义百炼平台鉴权 header
              headers:
                Authorization: Bearer ${AI_DASHSCOPE_API_KEY}

  mandatory-file-encoding: UTF-8