spring:
  ai:
    mcp:
      server:
        name: my-weather-server
        version: 0.0.1
        type: ASYNC
        sse-endpoint: /sse
        sse-message-endpoint: /mcp
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

# logging.pattern.console=
